# Generated by Django 5.2.7 on 2025-11-26 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subject', models.CharField(choices=[('lang', 'Language Arts'), ('math', 'Mathematics'), ('sci', 'Science'), ('ss', 'Social Studies'), ('art', 'Arts & Creative'), ('pe', 'Physical Education'), ('other', 'Other')], max_length=10)),
                ('level', models.CharField(choices=[('elem', 'Elementary'), ('middle', 'Middle School'), ('high', 'High School'), ('all', 'All Ages')], max_length=10)),
                ('description', models.TextField()),
                ('objectives', models.TextField(help_text='Learning objectives for this lesson')),
                ('materials', models.TextField(blank=True, help_text='Materials and resources needed')),
                ('duration_minutes', models.IntegerField(default=60)),
                ('lesson_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-lesson_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='core.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
